In [ ]:
### Si no se cuenta con sqlalchemy
!pip install pyglet

In [1]:
import sys
import mysql.connector

import sqlalchemy
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import os
import plotly.express as px

## Establecer conexión MySQL

Nota: Considera que debes tener una base de datos creada llamada pruebas, la cual deberás crear, con dos tablas: customer y orders.

Una alternativa es probar las conexiones con una base de datos que tengas en MySQL

In [11]:
#engine = sqlalchemy.create_engine("mysql+pymysql://user:password@host:puerto/database")
engine = sqlalchemy.create_engine("mysql+pymysql://root:@localhost:3306/pruebas")

### Leer tablas desde MySQL a Pandas

In [5]:
df = pd.read_sql_table("customer", engine)
df

   id             name phone_number
0   1         Karl Jab    111222333
1   2       Matti Kart    223123243
2   3        Tom Erich   2123214231
3   4     rafael nadal   1231423545
4   5  maria sharapova   1423542534
5   6   vladimir putin   2345253435
6   7     rafael nadal   1231423545
7   8  maria sharapova   1423542534
8   9   vladimir putin   2345253435

In [6]:
df = pd.read_sql_table("orders", engine)
df

   id          name  amount  customer_id
0   1      Yoga Mat      20            2
1   2  Google Pixel     950            1
2   3  Fossil Watch     120            3

### Crear querys desde MySQL a Pandas

In [12]:
query = """
SELECT customer.name, customer.phone_number, orders.name, orders.amount
FROM customer 
INNER JOIN orders
ON customer.id = orders.customer_id
"""
df = pd.read_sql_query(query, engine)
df

         name phone_number          name  amount
0  Matti Kart    223123243      Yoga Mat      20
1    Karl Jab    111222333  Google Pixel     950
2   Tom Erich   2123214231  Fossil Watch     120

### Escribir tablas de Pandas a MySQL

In [13]:
df = pd.read_csv('customers_prueba.csv')
df.rename(columns = {
    'Customer Name':'name',
    'Customer Phone': 'phone_number'
}, inplace = True)
df

              name  phone_number
0     rafael nadal    1231423545
1  maria sharapova    1423542534
2   vladimir putin    2345253435

In [17]:
df.to_sql(
    name = 'customer',
    con = engine,
    index = False,
    if_exists = 'append'
)

3

In [18]:
pd.read_sql('customer', engine)

    id             name phone_number
0    1         Karl Jab    111222333
1    2       Matti Kart    223123243
2    3        Tom Erich   2123214231
3    4     rafael nadal   1231423545
4    5  maria sharapova   1423542534
5    6   vladimir putin   2345253435
6    7     rafael nadal   1231423545
7    8  maria sharapova   1423542534
8    9   vladimir putin   2345253435
9   10     rafael nadal   1231423545
10  11  maria sharapova   1423542534
11  12   vladimir putin   2345253435
12  13     rafael nadal   1231423545
13  14  maria sharapova   1423542534
14  15   vladimir putin   2345253435

In [19]:
df.to_sql(
    name = 'customer3',
    con = engine,
    index = False,
    if_exists = 'append'
)

3

### Leer tablas / querys

In [22]:
df = pd.read_sql('customer3', engine)
df

              name  phone_number
0     rafael nadal    1231423545
1  maria sharapova    1423542534
2   vladimir putin    2345253435

In [23]:
df = pd.read_sql(query, engine)
df

         name phone_number          name  amount
0  Matti Kart    223123243      Yoga Mat      20
1    Karl Jab    111222333  Google Pixel     950
2   Tom Erich   2123214231  Fossil Watch     120